name: rustup
description: "Dart bindings for the rustup CLI tool."
version: 0.1.0-dev.1
homepage: https://github.com/irondash/native_toolchain_rust.git

environment:
  sdk: ">=3.4.0-190.0.dev <4.0.0"

dependencies:
  native_toolchain_rust_common: ^0.1.0-dev.1
  process: ^5.0.2
  pub_semver: ^2.1.4
  native_assets_cli: ^0.5.4
  http: ^1.2.1
  logging: ^1.2.0
  path: ^1.9.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
