name: native_toolchain_rust_common
description: Common code for native_toolchain_rust and native_doctor.
version: 0.1.0-dev.1
homepage: https://github.com/irondash/native_toolchain_rust.git

environment:
  sdk: ^3.5.0-90.0.dev

dependencies:
  logging: ^1.2.0
  pub_semver: ^2.1.4
  source_span: ^1.10.0
  package_config: ^2.1.0
  yaml: ^3.1.2

  # FakeProcessManager
  process: ^5.0.2
  file: ^7.0.0
  meta: ^1.12.0
  test: ^1.21.0

dev_dependencies:
  lints: ^3.0.0
