name: native_toolchain_rust
description: A library to invoke Rust installed on the host machine. Intended for building native assets.
version: 0.1.0-dev.1
homepage: https://github.com/irondash/native_toolchain_rust.git
publish_to: none

environment:
  sdk: ">=3.4.0-190.0.dev <4.0.0"

dependencies:
  native_toolchain_rust_common: ^0.1.0-dev.1
  collection: ^1.18.0
  logging: ^1.2.0
  native_assets_cli: ^0.5.4
  path: ^1.9.0
  process: ^5.0.2
  pub_semver: ^2.1.4
  toml: ^0.15.0
  rustup: ^0.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

